version: '3.7'

services:
  web:
    build: .
    command: -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
    volumes:
      - ./:/usr/src/app/
      - ~/Downloads/target:/opt/target
      - ~/Downloads/source:/opt/source
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data: